// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6MxQ0iKay-ibVhwnRo7_vimzR8Ndzxvw',
    appId: '1:199138869701:web:bce38c24ffac85ea550bac',
    messagingSenderId: '199138869701',
    projectId: 'watering-112ed',
    authDomain: 'watering-112ed.firebaseapp.com',
    storageBucket: 'watering-112ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPz4t-cdN8fw64lW7GIzKdqTULutnV1Vg',
    appId: '1:199138869701:android:e1b3997937bcf271550bac',
    messagingSenderId: '199138869701',
    projectId: 'watering-112ed',
    storageBucket: 'watering-112ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuIjFKVteabZXAx8lPQlzjGuW8Q_ClDo',
    appId: '1:199138869701:ios:d43a7bb7149221b3550bac',
    messagingSenderId: '199138869701',
    projectId: 'watering-112ed',
    storageBucket: 'watering-112ed.appspot.com',
    iosClientId: '199138869701-oo9q2jua6qhvslla3ctsspfkg1ci3b4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.uacjApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhuIjFKVteabZXAx8lPQlzjGuW8Q_ClDo',
    appId: '1:199138869701:ios:dd5330682164f64d550bac',
    messagingSenderId: '199138869701',
    projectId: 'watering-112ed',
    storageBucket: 'watering-112ed.appspot.com',
    iosClientId: '199138869701-e1dvssoojhg2jbangh4s73go7t8kuf93.apps.googleusercontent.com',
    iosBundleId: 'com.example.uacjApp.RunnerTests',
  );
}
